#!/bin/bash

set -o pipefail
set -o errexit
set -o nounset

#arg1 = reference fasta
#arg2 = bam file
#arg3 = output cram

if [[ "$#" -lt 3 ]]; then
    echo "not enough parameters specified. Expected refFasta, bamFile, and output cram"
    exit 1
fi
/opt/samtools/bin/samtools view -T "$1" -C -O cram -o "$3" "$2"
/opt/samtools/bin/samtools index "$3"
