#!/bin/bash

set -o pipefail
set -o errexit
set -o nounset

#arg1 = /path/to/input/biscuit_pileup.vcf 
#arg2 = /path/to/reference.fa
#arg3 = /path/to/output/cpgs.bed.gz
#arg4 = /path/to/output/cpgs.bedgraph

#Creates a gzipped bed and a bedgraph that leaves out MT, random, GL contigs, etc
if [[ "$#" -lt 4 ]]; then
    echo "not enough parameters specified. Expected biscuit_vcf, reference_fasta, output_cpgs.bed.gz, output_cpgs.bedgraph"
    exit 1
fi

/usr/bin/biscuit vcf2bed -t cg -k 1 -e "$1" | /usr/bin/biscuit mergecg "$2" /dev/stdin -k 2 |  tee >(/bin/gzip >"$3") | cut -f 1-4 | sort -k1,1 -k2,2n -S 12G | /usr/bin/perl -ne 'print $_ if $_ =~ /^(chr)?[1-9]?[0-9|X|Y]\s/' >"$4"
